coffee_rescuer/apps/finca/urls.py
from django.urls import path
from apps.finca.views import mapa_view, editor_view

app_name = "finca"
urlpatterns = [
    path('<int:id_finca>/',mapa_view,name="mapa"),
    path('editor/<int:id_finca>/',editor_view,name="editor"),
]

coffee_rescuer/coffee_rescuer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,logout_then_login
from coffee_rescuer.views import mostrar_index,mostrar_nosotros,mostrar_galeria,mostrar_contactanos,predict
urlpatterns = [
    path('admin/', admin.site.urls),
    path('finca/', include('apps.finca.urls', namespace="finca")),
    path('lote/', include('apps.lote.urls', namespace="lote")),
    path('usuario/',include('apps.usuario.urls', namespace="usuario")),
    path('accounts/login/',LoginView.as_view(template_name='usuario/login.html'),name="login"),
    path('logout/',logout_then_login,name="logout"),
    path('', mostrar_index, name="index"),
    path('sobreNosotros/', mostrar_nosotros, name="sobre_nosotros"),
    path('galeria/', mostrar_galeria, name="galeria"),
    path('contactanos/', mostrar_contactanos, name="contactanos"),
    path('predict/', predict, name="predict")
]



coffee_rescuer/apps/finca/models.py
from django.core import serializers
from django.db import models
from django.contrib.auth.models import User
from coffee_rescuer.settings import BASE_DIR
from django.apps import apps
import os
from apps.lote.ETAPA_ROYA import ETAPA_ROYA


class Finca(models.Model):

    def __str__(self):
        return self.nombre if self.nombre else str(self.id)

    id = models.PositiveIntegerField(primary_key=True)
    nombre = models.CharField(null=True, blank=True, max_length=50)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    promedio_estado_lotes = models.PositiveIntegerField(default=0, choices=ETAPA_ROYA)


def obtener_coordenadas(id_finca):
    Lote = apps.get_model('lote', 'Lote')
    Coordenada = apps.get_model('lote', 'Coordenada')
    """
    Este método permite obtener las coordenadas de los lotes de una finca para pintarlos en el mapa.
    @param id_finca: El numero de identificación de la finca
    @return: Un diccionario con las coordenadas (x,y) de los lotes y su tamano, width y height (w,h)
    """
    lotes = Lote.objects.filter(finca=id_finca)
    coordenadas = {}
    for lote in lotes:
        try:
            coordenada = Coordenada.objects.get(lote=lote)
            coordenada = {"x": coordenada.x,"y": coordenada.y, "w": coordenada.width, "h": coordenada.height}
            coordenadas[lote.id] = coordenada
        except Exception as e:
            pass

    return coordenadas


coffee_rescuer/apps/finca/views.py
from django.shortcuts import render, redirect

from apps.finca.models import Finca
from apps.lote.models import Lote
from apps.finca.models import obtener_coordenadas
import json
from django.core import serializers
from django.contrib.auth.decorators import login_required
from apps.finca.form import EditorForm
from apps.lote.models import Coordenada
# Create your views here.


@login_required
def mapa_view(request, id_finca):
    """
    Este método permite mostrar la información de la página que contiene el mapa de la finca
    @param request: La petición al servidor
    @param id_finca:  El id de la finca de la que se mostrará el mapa
    """
    try:
        finca = Finca.objects.get(id=id_finca)
    except Exception:
        return redirect('index')
    if request.user.id != finca.usuario.id:
        return redirect('index')

    lotes = Lote.objects.filter(finca=id_finca)
    coordenadas = obtener_coordenadas(id_finca)
    etapas = {}
    for lote in lotes:
        detalle_lote_actual = lote.obtener_detalle_lote_actual()
        if detalle_lote_actual:
            etapas[lote.id] = detalle_lote_actual.etapa_hongo
        else:
            etapas[lote.id] = lote.ultimo_estado_hongo

    context = {"finca": finca,
               "lotes": serializers.serialize('json', lotes, fields=["id", "nombre"]),
               "etapas": json.dumps(etapas),
               "coordenadas": json.dumps(coordenadas)
               }
    return render(request, "finca/mapa.html", context)


def editor_view(request,id_finca):

    if request.method == "POST":
        form = EditorForm(request.POST)
        form.is_valid()
        jdata = form.cleaned_data['jsonfield']
        json_data = str(jdata )
        json_data = json.loads(json_data)
        for coordenada in json_data["datos"]:
            id_lote = int(coordenada["id"])
            lote = Lote.objects.get(id=id_lote)
            Coordenada.objects.filter(lote=id_lote).delete()
            Coordenada.objects.create(lote=lote, x=coordenada["x"], y=coordenada["y"], width=coordenada["w"],height=coordenada["h"])
        return redirect("finca:mapa", id_finca)
    form = EditorForm()
    lotes = Lote.objects.filter(finca=id_finca)
   # lotes = serializers.serialize('json', lotes, fields=["id", "nombre"])

    context = {"finca": id_finca,"form":form, "lotes": lotes}
    return render(request, "finca/editorMapa.html", context)

coffee_rescuer/templates/finca/editorMapa.html
{% extends "base/base.html" %}
{% block content %}
{% load json_filters %}
        <img src="https://preview.ibb.co/duMHYe/Imagen1.png" height="100" width="100">
        <h1>Editor de Mapas</h1>
        <form>
            <select id="mySelect" class="custom-select">
                            {% for lote in lotes %}
                                <option value="{{lote.id}}">{{lote}}</option>
                            {% endfor %}
            </select>
        </form>
        <h2 id="pintarLote"></h2>
        <button class="btn btn-primary mt-1" onclick="revertir()">Revertir</button>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-1" onclick="myFunction()">Exportar</button>
        </form>
        <br><br><br>


        <div class="container">
            <div class="row">
                <div class="col-12 pre-scrollable" style="min-height: 1000px;">
                    <div style="">
                        <canvas id="canvas" style="background:white;position:relative; border:1px solid #7B7B7B;">
                            Your browser does not support the HTML5 canvas tag.
                        </canvas>
                    </div>
                </div>

        </div>
        </div>

        <script >
            var currentId=-1;
            var currentName="";
            var pastId;
            var pastName;
            var pastX;
            var pastY;
            var pastW;
            var pastH;
            var historial = "{{lotes |jsonify }}".replace(/(&quot\;)/g, "\"");
            historial = JSON.parse(historial);
            function removerSeleccionado(x,y,w,h){
                var listaDesplegable = document.getElementById("mySelect");
                currentId = listaDesplegable.value;
                currentName = listaDesplegable.text;
                for (var i=0; i<listaDesplegable.length; i++){
                    if (listaDesplegable.options[i].value == currentId ){
                        pastId = currentId;
                        var name;
                        for (var j=0;j<historial.length;j++){
                            if(historial[j]["pk"]+""==(currentId+"")){
                                name =historial[j]["fields"]["nombre"];
                            }
                        }
                        if(name!=null)pastName = name;
                        pastX=x;
                        pastY=y;
                        pastW=w;
                        pastH=h;
                        listaDesplegable.remove(i);
                    }
                }
                currentId = parseInt(currentId);

            }

            function rgbToHex(rgb) {
                var hex = Number(rgb).toString(16);
                if (hex.length < 2) {
                    hex = "0" + hex;
                }
                return hex;
            }



            const canvas = document.getElementById('canvas');
            const ctx = canvas.getContext('2d');
            canvas.width = 1000;
            canvas.height = 500;

            function revertir() {
                if(pastId!=null){
                    var listaDesplegable = document.getElementById("mySelect");
                    var opt1 = document.createElement("option");
                    opt1.value = pastId;
                    if(pastName!=null)opt1.text = pastName;
                    else opt1.text = pastId;
                    listaDesplegable.add(opt1, null);
                    ctx.beginPath();
                    ctx.fillStyle = "#FFFFFF";
                    ctx.fillRect(pastX[pastX.length-1], pastY[pastY.length-1],pastW[pastW.length-1], pastH[pastH.length-1]);
                    ctx.fill();
                    pastId = null;
                    pastName = null;
                    pastX=null;
                    pastY=null;
                    pastW=null;
                    pastH=null;
                }
            }
            var i = 0;
            var coordX = new Array(2);
            var coordY = new Array(2);
            var dataX = new Array();
            var dataY = new Array();
            var dataW = new Array();
            var dataH = new Array();
            var names = new Array();
            var cont = 0;
            canvas.addEventListener('click', (e) => {

                function getMousePos(c, evt) {

                    var rect = c.getBoundingClientRect();
                    return {
                        x: evt.clientX,
                        y: evt.clientY
                    }
                }

                var pos = getMousePos(canvas,e);
                var canva = canvas.getBoundingClientRect();
                var mousePosx = pos.x - canva.left;
                var mousePosy = pos.y - canva.top;
                if (i < 2) {
                    coordX[i] = mousePosx;
                    coordY[i] = mousePosy;
                }
                i++;

                if (i == 2) {
                    var r = Math.floor((Math.random() * 255) + 1);
                    var g = Math.floor((Math.random() * 255) + 1);
                    var b = Math.floor((Math.random() * 255) + 1);
                    var r = rgbToHex(r);
                    var g = rgbToHex(g);
                    var b = rgbToHex(b);
                    ctx.beginPath();
                    ctx.fillStyle = "#" + r + g + b;
                    ctx.fillRect(coordX[0], coordY[0], coordX[1] - coordX[0], coordY[1] - coordY[0]);
                    ctx.fill();
                    dataX[cont] = coordX[0];
                    dataY[cont] = coordY[0];
                    dataW[cont] = coordX[1] - coordX[0];
                    dataH[cont] = coordY[1] - coordY[0];
                    removerSeleccionado(dataX,dataY,dataW,dataH);
                    names[cont] = currentId;
                    cont++;
                    i = 0;
                }
            });

            function myFunction() {
                var list = {
                    "datos": []
                };
                for (var i = 0; i < dataX.length; i++) {

                    var key = names[i];
                    list.datos.push({
                        "x": dataX[i],
                        "y": dataY[i],
                        "w": dataW[i],
                        "h": dataH[i],
                        "id": key
                    });
                }
                var json = JSON.stringify(list); // aqui tienes la lista de objetos en Json
                document.getElementById('infoNuevoMapa').value = json.toString();
            }
        </script>
{% endblock content %}

coffee_rescuer/templates/finca/mapa.html
{% extends "base/base.html" %}
{%load staticfiles%}
{% block extrastatic %}
  <link rel="stylesheet" href="{%static 'css/modalStyle.css'%}">

{% endblock extrastatic %}
{% block content %}
<canvas id="circle_finca" width="120" height="120"></canvas>
<SPAN style="position: absolute; top: 80 px; left 100 px; font-size: xx-large;">
    <br>
    {% if finca.nombre %}
     <b>{{finca.nombre}}</b>     
    {% else %}
     <b>Finca con id: {{finca.id}}</b>
    {% endif %}
   
</SPAN>

<hr>
    <div class="row">
    <div class="col-1.5 pl-4">
        <h1 id="Map">Mapa</h1>
    </div>
     <div class="col-2 py-2">

    <a class="btn btn-success" href="{% url 'finca:editor' finca.id%}">Crear Mapa</a>
          <button style="display:none;" type="button" id="showModal" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"></button>
     </div>
    </div>
    <br>
<div class="container">
        <div class="row">
            <div class="col-12 pre-scrollable" style="min-height: 1000px;" >
                <div style="">
                <canvas id="canva_mapa"  style="position:relative; border:1px solid #7B7B7B;" >
    Your browser does not support the HTML5 canvas tag.</canvas>
            </div>
        </div>

</div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog w-100" role="document" style="min-height: 800px; ">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Información de lote</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >
        <iframe id="loteFrame" class="w-100" style="min-height: 500px;"  frameborder="0"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<script>
    var jsonContextoCoordenadas = "{{coordenadas}}".replace(/(&quot\;)/g,"\"");
    var jsonContextoEtapas = "{{etapas}}".replace(/(&quot\;)/g,"\"");
    var jsonContextoLotes = "{{lotes}}".replace(/(&quot\;)/g,"\"");
    var prom = "{{finca.promedio_estado_lotes}}";

    function f(i) {
        var frame = document.getElementById('loteFrame');
        frame.src ="http://sinroya.dis.eafit.edu.co/lote/"+i;
        document.getElementById("showModal").click();
    }
</script>
<script src="{%static 'js/canvas.js'%}"></script>
<script src="{%static 'js/mapa.js'%}"></script>
{% endblock content %}